#!/usr/bin/env python3
"""
解析 Top20_sample_video_url.txt → assets/sample-videos.js
生成 SAMPLE_VIDEOS = { "category|author": [{title, video_url, channel_url, rk}, ...] }
"""
import csv
import json
import os
from collections import defaultdict

SRC = "/Users/ehjiang/Desktop/漫游数据源盘点/Top20_sample_video_url.txt"
OUT = "/Users/ehjiang/Desktop/channel-sourcing-analysis/assets/sample-videos.js"


def js_repr(v):
    """JSON-safe repr for JS (handles None, str, number, list, dict)."""
    return json.dumps(v, ensure_ascii=False)


def main():
    grouped = defaultdict(list)
    total = 0
    with open(SRC, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            # 兼容尾行没有 \n 把 rk 吞掉的情况
            rk_raw = (row.get("rk") or "").strip()
            try:
                rk = int(rk_raw)
            except ValueError:
                rk = 0
            cat = (row.get("unified_category") or "").strip()
            author = (row.get("author") or "").strip()
            title = (row.get("obj_title") or "").strip()
            video_url = (row.get("sample_video_url") or "").strip()
            channel_url = (row.get("sample_channel_url") or "").strip()
            if not cat or not author:
                continue
            key = f"{cat}|{author}"
            grouped[key].append({
                "rk": rk,
                "title": title,
                "video_url": video_url,
                "channel_url": channel_url if channel_url and channel_url.upper() != "NULL" else None,
            })
            total += 1

    # 每组内按 rk 排序
    for key in grouped:
        grouped[key].sort(key=lambda r: r["rk"])

    # 统计信息
    cats = set(k.split("|", 1)[0] for k in grouped.keys())
    print(f"读取 {total} 行采样数据")
    print(f"覆盖 {len(grouped)} 个 (类目, channel) 对")
    print(f"覆盖 {len(cats)} 个类目")

    # 输出 JS 文件
    lines = [
        "/**",
        " * 漫游数据源盘点 - 每个 channel 的随机采样视频示例",
        " * Auto-generated by scripts/parse_sample_videos.py",
        " * Source: 漫游数据源盘点/Top20_sample_video_url.txt",
        " *",
        " * 结构: SAMPLE_VIDEOS[\"<unified_category>|<author>\"] = [",
        " *   { rk, title, video_url, channel_url }, ...",
        " * ]",
        " *",
        f" * 共 {total} 行采样视频, 覆盖 {len(grouped)} 个 channel, {len(cats)} 个类目",
        " */",
        "",
        "const SAMPLE_VIDEOS = {",
    ]
    for key in sorted(grouped.keys()):
        safe_key = key.replace("\\", "\\\\").replace('"', '\\"')
        rows = grouped[key]
        lines.append(f'  "{safe_key}": [')
        for r in rows:
            lines.append(f"    {js_repr(r)},")
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    # 辅助函数
    lines.append("// 查询函数: 给定 category + author, 返回采样视频数组 (没有则空数组)")
    lines.append("function getSampleVideos(category, author) {")
    lines.append("  if (!category || !author) return [];")
    lines.append("  return SAMPLE_VIDEOS[category + '|' + author] || [];")
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\n✓ 写入: {OUT}")
    print(f"  文件大小: {os.path.getsize(OUT) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
